# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Paul McAvoy
tagline:          'Homepage'
description:      'Blog by Paul McAvoy, Built with the Hyde Jekyll Theme by <a href="https://twitter.com/mdo">@mdo</a>.'
baseurl:          https://paulmca860.github.io/

author:
  name:           'Paul McAvoy'

paginate:         5

github:
  repo:           https://github.com/paulmca860/paulmca860.github.io
